drop database prueba2;
create database prueba2;
use prueba2;

DROP TABLE IF EXISTS APPROVER;
CREATE TABLE APPROVER(
	APPROVER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    POSITION_ID INT NOT NULL,
    DEPTO_ID INT NOT NULL
);

CREATE TABLE DOC_APPROVER(
	DOC_APPROVER_ID INT PRIMARY KEY AUTO_INCREMENT,
    DOC_FLOW_ID INT NOT NULL,
    APPROVER_ID INT NOT NULL,
    SEQUENCE VARCHAR(100), /*---NO ESTOY SEGURO DE ESTE VALOR---*/
    NAME VARCHAR(100) NOT NULL,
    ACTION INT DEFAULT TRUE /*--NO ESTOY SEGURO DE ESTE VALOR--*/
);


CREATE TABLE DOC_FLOW(
	DOC_FLOW_ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_ID INT NOT NULL,
    KEY1 VARCHAR(100),
    KEY2 VARCHAR(100),
    KEY3 VARCHAR(100),
    KEY4 VARCHAR(100)
);


/*AGREGAR FOREIGN KEY EN DOC_FLOW->TYPE_ID*/

CREATE TABLE DOC_TYPE(
	TYPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_CODE VARCHAR(100)
);

CREATE TABLE DOCUMENT(
	DOCUMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    TYPE_ID INT NOT NULL
);


CREATE TABLE DOC_FILE(
	FILE_ID INT PRIMARY KEY AUTO_INCREMENT,
    DOCUMENT_ID INT NOT NULL,
    DOC_IMG VARCHAR(100)
);

ALTER TABLE DOC_APPROVER
ADD CONSTRAINT KF_DOC_FLOW_ID
FOREIGN KEY (DOC_FLOW_ID) REFERENCES DOC_FLOW(DOC_FLOW_ID);

ALTER TABLE DOC_APPROVER 
ADD CONSTRAINT FK_APPROVER_ID 
FOREIGN KEY (APPROVER_ID) REFERENCES APPROVER(APPROVER_ID);


ALTER TABLE DOC_FLOW
ADD CONSTRAINT FK_TYPE_ID
FOREIGN KEY (TYPE_ID) REFERENCES DOC_TYPE(TYPE_ID);


ALTER TABLE DOCUMENT
ADD FOREIGN KEY (TYPE_ID) REFERENCES DOC_TYPE(TYPE_ID);

ALTER TABLE DOC_FILE
ADD CONSTRAINT FK_DOCUMENT_ID
FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID);