USE CTL_HINT;

/* ############################# DEVICE ############################### */

DROP TABLE IF EXISTS DEV_CONNECTION;
CREATE TABLE DEV_CONNECTION (
	DEVICE_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEVICE_NAME VARCHAR(100) NOT NULL,
    DEVICE_MODEL VARCHAR(300),
    IP_ADDRESS INT NOT NULL DEFAULT 0,
    IS_ACTIVE BOOL NOT NULL DEFAULT TRUE,
    LAST_UPDATE DATETIME NOT NULL DEFAULT NOW()
);

DROP TABLE IF EXISTS DEV_FLOW;
CREATE TABLE DEV_FLOW (
	DEVICE_ID INT PRIMARY KEY,
    FLOW_ID INT NOT NULL,
    LAST_UPDATE DATETIME NOT NULL DEFAULT NOW()
);

ALTER TABLE DEV_FLOW ADD CONSTRAINT FK_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEV_CONNECTION (DEVICE_ID),
					 ADD CONSTRAINT FK_DEVICE_FLOW FOREIGN KEY (FLOW_ID) REFERENCES FLOW_SERVICE (FLOW_ID);