/*######################### VW_FLOW_CONFIGURATION ##############################*/
DROP VIEW IF EXISTS VW_FLOW_CONFIGURATION;
CREATE VIEW VW_FLOW_CONFIGURATION AS
    SELECT 
		FS.FLOW_ID,
		FS.FLOW_NAME,
		FD.FLOW_DET_ID,
		FD.SEQUENCE,
		FD.IS_REQUIRED,    
		FD.DESCRIPTION,
		CA.API_ID,
		CA.URL_BASE,
		FD.ENDPOINT_ID,
		CUE.ENDPOINT,
		CUE.REQUEST_TYPE		
	FROM
		FLOW_SERVICE FS JOIN FLOW_DETAIL FD ON FD.FLOW_ID = FS.FLOW_ID 
						JOIN CON_URL_ENDPOINT CUE ON CUE.ENDPOINT_ID = FD.ENDPOINT_ID
						JOIN CON_API CA ON CA.API_ID = CUE.API_ID;									