
/*######################### GET_DEVICE ##############################*/
DROP FUNCTION IF EXISTS GET_DEVICE ;
DELIMITER //
CREATE FUNCTION GET_DEVICE(
	IN_DEVICE_NAME VARCHAR(100)
) RETURNS INT DETERMINISTIC
BEGIN
	DECLARE VL_DEVICE_ID INT DEFAULT NULL;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION 
    BEGIN 
		SET VL_DEVICE_ID = NULL;
    END;	
    
    SELECT 
		DEVICE_ID INTO VL_DEVICE_ID 
	FROM 
		DEV_CONNECTION 
	WHERE DEVICE_NAME = IN_DEVICE_NAME;
    
    RETURN VL_DEVICE_ID;
    
END //
DELIMITER ;
-- SELECT GET_DEVICE('ESP-FG-TNT') AS DEVICE_ID;

/*######################### VW_FLOW_CONFIGURATION ##############################*/
DROP VIEW IF EXISTS VW_FLOW_CONFIGURATION;
CREATE VIEW VW_FLOW_CONFIGURATION AS
    SELECT 
		FS.FLOW_ID,
		FS.FLOW_NAME,
		FD.FLOW_DET_ID,
		FD.SEQUENCE,
		FD.IS_REQUIRED,    
		FD.DESCRIPTION,
		CA.API_ID,
		CA.URL_BASE,
		FD.ENDPOINT_ID,
		CUE.ENDPOINT,
		CUE.REQUEST_TYPE		
	FROM
		FLOW_SERVICE FS RIGHT JOIN FLOW_DETAIL FD ON FD.FLOW_ID = FS.FLOW_ID 
						RIGHT JOIN CON_URL_ENDPOINT CUE ON CUE.ENDPOINT_ID = FD.ENDPOINT_ID
						RIGHT JOIN CON_API CA ON CA.API_ID = CUE.API_ID;									
                        
use ctl_hint;

SELECT * FROM VW_FLOW_CONFIGURATION;