SELECT 
	CA.API_ID, 
    CA.DESCRIPTION API_DESCRIPTION, 
    CA.URL_BASE, 
    CUE.ENDPOINT_ID, 
    CUE.ENDPOINT, 
    CUE.REQUEST_TYPE
FROM 
	CON_API CA JOIN CON_URL_ENDPOINT CUE ON CA.API_ID = CUE.API_ID;
    
SELECT 
	 TH.TXN_ID,
     TH.FLOW_ID,
     TH.FLOW_NAME,
     TH.TXN_STS_ID,
     TH.TXN_STS,
     TD.TXN_DET_ID,
     TD.ENDPOINT_ID,
     TD.TXN_STS_ID STATUS_DETAIL_ID,
     TD.TXN_STS STATUS_DETAIL
FROM 
	TXN_HEADER TH JOIN TXN_DETAIL TD ON TH.TXN_ID = TD.TXN_ID;
    
SELECT * FROM CON_API;
SELECT * FROM CTL_ACCESS.EMPLOYEE;


SELECT ifnull('YA NO ES NULL', NULL);

call get_flow(null, null, null, @out_result)